// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsMzLite")>]
[<assembly: AssemblyProductAttribute("FsMzLite")>]
[<assembly: AssemblyDescriptionAttribute("FsMzLite is a scripting friendly Wrapper for the MzLite library.")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsMzLite"
    let [<Literal>] AssemblyProduct = "FsMzLite"
    let [<Literal>] AssemblyDescription = "FsMzLite is a scripting friendly Wrapper for the MzLite library."
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
